[project]
name = "djangosaas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.5",
    "gunicorn>=23.0.0",
    "python-decouple>=3.8",
]
